spring:
  profiles:
    active: development
  application:
    name: Tapp-Application
  mail:
        host: smtp.gmail.com
        port: 587
        username: paras.vankadi@gmail.com
        password: test
        protocol:
        properties:
          mail:
            smtp:
              auth: true
              ssl.trust: smtp.gmail.com
              starttls:
                enable: true
                required: true
             
server:
  servlet:
    context-path: /tapp/api
---
server:
  port: 8080
spring:
  profiles: development
  servlet:
    multipart:
      max-file-size: 10MB
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/tapp_application?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: Hikari-Connection-Pool
      connection-timeout: 60000
      minimum-idle: 10
      maximum-pool-size: 50
      idle-timeout: 300000
      max-lifetime: 1200000
      connection-test-query: SELECT 1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
logging:
  level:
    root: INFO
  file: D:/temp/tapp-storage/logs/app-log.log
